### ISSUE TITLE
feature request - noscope every x rounds

### ISSUE THREAD

**Issue by dzagu** [zakriamansoor47/SLAYER_Noscope#1]
Hi, can you add feature where there is noscope round every x rounds?

**Comment by zakriamansoor47** [comment]
> Hi, can you add feature where there is noscope round every x rounds?

I am not adding that feature in this plugin, you have to use my **[this](https://github.com/zakriamansoor47/SLAYER_Duel)** plugin 
to set no scope round after every x rounds.
